### ISSUE TITLE
Laravel 4.1

### ISSUE THREAD

**Issue by dylanlindgren** [skovachev/fakefactory#1]
Would it be possible to get this package compatible with Laravel 4.1? It's set to require Laravel 4.0 however I don't think 4.1 was a big change so there may not be much work to do apart from updating the composer.json.

I'm still getting up to speed with Laravel, composer, tests, packages etc so don't really feel my coding is up to the level where I could do this myself :(

**Comment by skovachev** [comment]
I've updated the composer.json file. Should be fine now.

**Comment by dylanlindgren** [comment]
Amazing, thanks so much!
